### ISSUE TITLE
Double && causes popup error

### ISSUE THREAD

**Issue by LadyCailin** [LadyCailin/MethodScriptVSC#12]
`@val = true && && true` causes a java exception, which causes a popup window.

In particular, there is a stacktrace:

```
java.lang.Error: Native class class com.laytonsmith.core.constructs.CSymbol does not provide a typeof annotation
	at com.laytonsmith.core.FullyQualifiedClassName.forNativeClass(FullyQualifiedClassName.java:109)
	at com.laytonsmith.core.constructs.CClassType.get(CClassType.java:108)
	at com.laytonsmith.core.constructs.Construct.typeof(Construct.java:497)
	at com.laytonsmith.core.constructs.Construct.typeof(Construct.java:487)
	at com.laytonsmith.core.ArgumentValidation.getBooleanish(ArgumentValidation.java:381)
	at com.laytonsmith.core.ArgumentValidation.getBoolean(ArgumentValidation.java:354)
	at com.laytonsmith.core.functions.BasicLogic$and.optimizeDynamic(BasicLogic.java:1070)
	at com.laytonsmith.core.MethodScriptCompiler.optimize(MethodScriptCompiler.java:2312)
	at com.laytonsmith.core.MethodScriptCompiler.optimize(MethodScriptCompiler.java:2333)
	at com.laytonsmith.core.MethodScriptCompiler.optimize(MethodScriptCompiler.java:2208)
	at com.laytonsmith.core.MethodScriptCompiler.optimize(MethodScriptCompiler.java:2208)
	at com.laytonsmith.core.MethodScriptCompiler.compile(MethodScriptCompiler.java:1765)
	at com.laytonsmith.tools.langserv.LangServ.lambda$doCompilation$9(LangServ.java:587)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by PseudoKnight** [comment]
This appears to be fixed, maybe due to the addition of statements. 

Just for the record: it now results (with strict mode enabled) in "Unexpected statement" and "Unexpected symbol" exceptions on the first `&&`, as well as "Not a statement" exception on the last `true`. With static analysis enabled, there's an additional "Unsupported AST node implementation in type checking: CSymbol" on the second `&&`. With strict mode off, it just gets the "Unexpected symbol" exception.

**Comment by Pieter12345** [comment]
> This appears to be fixed, maybe due to the addition of statements.
> 
> Just for the record: it now results (with strict mode enabled) in "Unexpected statement" and "Unexpected symbol" exceptions on the first `&&`, as well as "Not a statement" exception on the last `true`. With static analysis enabled, there's an additional "Unsupported AST node implementation in type checking: CSymbol" on the second `&&`. With strict mode off, it just gets the "Unexpected symbol" exception.

I believe the issue here to be that a `CSymbol` makes it through the parsing and rewriting stages of the compiler. Static Analysis is not supposed to run on a syntactically invalid AST. I haven't looked at the code with this issue in mind, but I think that there's a function that loops over the code after handling `postParseRewrite()`, before Static Analysis and optimization. I believe that this loop should catch cases where code in syntactically incorrect and abort compilation there.

**Comment by PseudoKnight** [comment]
I think I found the commit that fixed this: https://github.com/EngineHub/CommandHelper/commit/2f7b2dc2b737ecc5728e27b4640c4d0748e9cc73

However, I'm working on detecting these earlier in compilation.
